'use client';

import React, { useCallback } from 'react';
import { Download, Printer } from 'lucide-react';

export default function ShareActions({ claims }) {
  const handleExportCSV = useCallback(() => {
    if (!claims || !claims.length) return;
    const headers = ['Claim', 'Supported', 'Evidence'];
    const rows = claims.map(c => [
      `"${c.claim.replace(/"/g, '""')}"`,
      c.supported ? 'Yes' : 'No',
      `"${(c.evidence || '').replace(/"/g, '""')}"`
    ]);
    const brandingHeader = ['Generated by Ruju.ai - The B2B Anti-Hallucination Engine', '', ''];
    const csvContent = [brandingHeader.join(','), headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Ruju_Verification_Report_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [claims]);

  return (
    <div className="flex flex-wrap justify-center items-center gap-2 mt-6 print:hidden">
      <button onClick={handleExportCSV} className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 text-xs font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
        <Download size={14} /> Export CSV
      </button>
      <button onClick={() => window.print()} className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 text-xs font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
        <Printer size={14} /> Print Report
      </button>
    </div>
  );
}
